import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import OperationTable from '../components/OperationTable'
import StatWidget from '../components/StatWidget'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='bg-slate-100 min-h-[88vh]'>
      <Head>
        <title>Gestion comptable </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='max-w-5xl mx-auto bg-white'>
        <div className='flex items-center justify-between '>
          <StatWidget listOps={[]} />
          <Link href={"/payment/entree"}>
            <button className='text-white bg-blue-600 rounded-md px-10 py-2'>Nouvelle facturation</button>
          </Link>
        </div>
        <OperationTable />
      </main>


    </div>
  )
}
